#!/usr/bin/env bash
# Build and run UHC's fullstack web server as one indivisible operation.
#
# Do not replace this with `cargo run`: Dioxus Settings needs the matching WASM
# hydration bundle generated by `dx build`, not just a freshly compiled server.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

# Prefer cargo-installed dioxus-cli over any system dx (e.g., Deno's dx alias)
DX="${HOME}/.cargo/bin/dx"
if [[ ! -x "$DX" ]]; then
  echo "UHC web runner requires Dioxus CLI: cargo install dioxus-cli@0.7.10 --locked" >&2
  exit 1
fi

make css

# Some development machines configure Cargo to use sccache, which can prevent
# Dioxus from probing the wasm target. Override it only for this deterministic
# fullstack build.
CARGO_BUILD_RUSTC_WRAPPER='' "$DX" build --release --platform web --features web --bin unified-hifi-control

server="$repo_root/target/dx/unified-hifi-control/release/web/server"
if [[ ! -x "$server" ]]; then
  echo "Dioxus completed without a runnable fullstack server: $server" >&2
  exit 1
fi

echo "Starting freshly built UHC web server on port ${UHC_PORT:-8088}"
exec env PORT="${UHC_PORT:-8088}" "$server"
